# Generated by Django 4.1.7 on 2023-05-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_organization_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_img',
            field=models.ImageField(default='conventions/no-image-icon-21.png', upload_to='organizations'),
        ),
    ]
