# Generated by Django 4.1.7 on 2023-05-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventions',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='conventions',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
