# Generated by Django 4.1.7 on 2023-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0002_alter_conventions_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventions',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
