# Generated by Django 4.1.7 on 2023-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventions',
            name='convetion_img',
            field=models.ImageField(default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-21.png', upload_to=''),
        ),
    ]
