# Generated by Django 4.1.7 on 2023-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0003_alter_conventions_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(),
        ),
    ]
