# Generated by Django 4.1.7 on 2023-04-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0004_alter_conventions_convetion_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conventions',
            old_name='convetion_img',
            new_name='convention_img',
        ),
    ]
