# Generated by Django 4.1.7 on 2023-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0005_rename_convetion_img_conventions_convention_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventions',
            name='convention_img',
            field=models.ImageField(upload_to='media/covers'),
        ),
    ]
