# Generated by Django 4.1.7 on 2023-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0007_alter_conventions_convention_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventions',
            name='convention_img',
            field=models.ImageField(default='conventions/560TzipiVimages_0504040602.jpg', upload_to='conventions'),
        ),
    ]
