# Generated by Django 4.1.7 on 2023-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='last known latitude'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='last known longitude'),
        ),
    ]
