# Generated by Django 4.1.7 on 2023-04-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_lat_alter_userprofile_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='profiles/no-profile-picture.svg', upload_to='profiles'),
        ),
    ]
