# Generated by Django 4.1.7 on 2023-05-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_company_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='conventions/no-profile-picture.svg', upload_to='profiles'),
        ),
    ]
