# Generated by Django 4.1.7 on 2023-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='conventions/no-image-icon-21.png', upload_to='profiles'),
        ),
    ]
