# Generated by Django 4.1.7 on 2023-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
